import { gql } from '@apollo/client';
import { useQuery } from '~/hooks/useQuery';

export function useGetAutogeneratedSubtitles() {

  const query = useQuery();

  return (assetId: string) => {
    return query<string>({
      name: 'getSubtitleMedia',
      query: gql`
        query GetSubtitleMedia($assetId: String!) {
          getSubtitleMedia(assetId: $assetId)
        }
      `,
      variables: { assetId },
      fetchPolicy: 'network-only'
    });
  };
}
